name: Get full info

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install tsx

      - name: Generate
        run: npx tsx .github/workflows/scripts/extract-metadata.ts

      - name: Release latest full info
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: full-info.json
          fail_on_unmatched_files: true