name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Detect changed files
      uses: yumemi-inc/changed-files@v3
      id: changes

    - name: Validate
      uses: symbioticfi/metadata-validation-scripts@image-validation
      with:
        files: ${{ steps.changes.outputs.files }}
        issue: ${{ github.event.number }}
        # token: ${{ secrets.GITHUB_TOKEN }}